server:
  port: 8082

spring:
  application:
    name: library-service
  cloud:
    config:
      name: library-service

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5