server:
  port: 8761

spring:
  application:
    name: service-discovery
  cloud:
    config:
      name: service-discovery

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false