server:
  port: 8081

spring:
  application:
    name: student-service
  cloud:
    config:
      name: student-service

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5